import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";
import UserDropdown from "@/components/user-dropdown";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import { ChartColumnBigIcon } from "lucide-react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import { Toaster } from "sonner";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${poppins.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <nav className="bg-background flex h-16 items-center justify-between border-b p-4 text-white">
              <Link
                href="/"
                className="flex text-primary items-center gap-1 text-2xl font-bold"
              >
                <ChartColumnBigIcon className="text-lime-500" /> NextCash
              </Link>
              <div>
                <NavigationMenu className="">
                  <NavigationMenuList>
                    <NavigationMenuItem className="relative">
                      <NavigationMenuTrigger className="text-primary">
                        Portfolios
                      </NavigationMenuTrigger>
                      <NavigationMenuContent>
                        <NavigationMenuLink asChild>
                          <Link href="/dashboard">Dashboard</Link>
                        </NavigationMenuLink>
                        <NavigationMenuLink asChild>
                          <Link href="/dashboard/portfolio/trades">Trades</Link>
                        </NavigationMenuLink>
                      </NavigationMenuContent>
                    </NavigationMenuItem>
                    <NavigationMenuItem className="relative">
                      <NavigationMenuTrigger className="text-primary">
                        Net-worth
                      </NavigationMenuTrigger>
                      <NavigationMenuContent>
                        <NavigationMenuLink asChild>
                          <Link href="/net-worth/budget">Budget</Link>
                        </NavigationMenuLink>
                      </NavigationMenuContent>
                    </NavigationMenuItem>
                  </NavigationMenuList>
                </NavigationMenu>
              </div>
              <div>
                <SignedOut>
                  <div className="flex items-center">
                    <Button asChild variant="link" className="text-white">
                      <SignInButton />
                    </Button>
                    <Button asChild variant="link" className="text-white">
                      <SignUpButton />
                    </Button>
                  </div>
                </SignedOut>
                <SignedIn>
                  <UserDropdown />
                </SignedIn>
              </div>
            </nav>

            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
