import { LanguageDropdown } from "@/components/lang-dropdown";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";

import NavbarMenu from "@/components/navbar-menu";
import UserDropdown from "@/components/user-dropdown";
import { Link } from "@/i18n/navigation";
import { routing } from "@/i18n/routing";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import { ChartColumnBigIcon } from "lucide-react";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Poppins } from "next/font/google";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <ClerkProvider>
      <html suppressHydrationWarning>
        <body className={`${poppins.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider locale={locale} messages={messages}>
              <nav className="bg-background flex h-16 items-center justify-between border-b p-4 text-white">
                <div className="flex gap-10">
                  <Link
                    href="/"
                    className="text-primary flex items-center gap-1 text-2xl font-bold"
                  >
                    <ChartColumnBigIcon className="text-lime-500" />
                    NextCash
                  </Link>
                  <SignedIn>
                    <NavbarMenu />
                  </SignedIn>
                </div>
                <div className="flex gap-1">
                  <LanguageDropdown />
                  <SignedOut>
                    <div className="flex items-center">
                      <Button asChild variant="link" className="text-primary">
                        <SignInButton />
                      </Button>
                      <Button asChild variant="link" className="text-primary">
                        <SignUpButton />
                      </Button>
                    </div>
                  </SignedOut>
                  <SignedIn>
                    <UserDropdown />
                  </SignedIn>
                </div>
              </nav>

              {children}
              <Toaster />
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
