import CurrencySelector from "@/components/currency-selector";
import { LanguageDropdown } from "@/components/lang-dropdown";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import { CurrencyProvider } from "@/contexts/currency-context";

import NavbarMenu from "@/components/navbar-menu";
import UserDropdown from "@/components/user-dropdown";
import { Link } from "@/i18n/navigation";
import { routing } from "@/i18n/routing";
import { ClerkProvider, Show, SignInButton, SignUpButton } from "@clerk/nextjs";
import { ChartColumnBigIcon } from "lucide-react";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Poppins } from "next/font/google";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <ClerkProvider>
      <html suppressHydrationWarning>
        <body className={`${poppins.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            storage="hybrid"
          >
            <NextIntlClientProvider locale={locale} messages={messages}>
              <CurrencyProvider>
                <div className="sticky top-0 z-40 px-3 pt-3 sm:px-5">
                  <nav className="glass-nav text-foreground mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-3 rounded-[2rem] px-4 py-3">
                    <div className="flex min-w-0 items-center gap-4 lg:gap-10">
                      <Link
                        href="/"
                        className="group text-foreground flex min-w-0 items-center gap-2 text-xl font-bold tracking-[-0.04em] sm:text-2xl"
                      >
                        <span className="glass-control text-primary flex size-10 items-center justify-center rounded-full shadow-sm transition-transform duration-300 group-hover:scale-105">
                          <ChartColumnBigIcon className="text-primary size-5" />
                        </span>
                        <span className="truncate">NextCash</span>
                      </Link>
                      <Show when="signed-in">
                        <NavbarMenu />
                      </Show>
                    </div>
                    <div className="flex shrink-0 items-center gap-2 sm:gap-3">
                      <CurrencySelector />
                      <LanguageDropdown />
                      <Show when="signed-out">
                        <div className="flex items-center gap-1">
                          <Button asChild variant="ghost" size="sm">
                            <SignInButton />
                          </Button>
                          <Button asChild size="sm">
                            <SignUpButton />
                          </Button>
                        </div>
                      </Show>
                      <Show when="signed-in">
                        <UserDropdown />
                      </Show>
                    </div>
                  </nav>
                </div>

                <main className="liquid-page px-3 pb-10 sm:px-5">
                  {children}
                </main>
                <Toaster />
              </CurrencyProvider>
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
